version: '2.1' 

services:

  web:
    build: ./backend/blog
    image: laravel-blog
    depends_on:
      - mysql
    volumes:
      - ./backend:/application/backend
      - ./frontend:/application/frontend
    mem_limit: 512m
    restart: always 
    links:
      - mysql
    
  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    links:
      - web
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/application/backend
      - ./frontend:/application/frontend
    depends_on:
      - web    
    mem_limit: 256m
    restart: always 

  mysql:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: galaxy
      MYSQL_PASSWORD: toor
      MYSQL_DATABASE: ingalaxy
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
